/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.boxcf.components.material;

import com.boxcf.models.LoaiSP;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.border.MatteBorder;

/**
 *
 * @author PC
 */
public class Category extends javax.swing.JPanel {

    private LoaiSP data;
    private boolean active;

    public boolean isActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
        if (active) {
            lblTitle.setForeground(new Color(56, 187, 156));
            lblTitle.setBorder(new MatteBorder(0, 0, 1, 0, new Color(56, 187, 156)));
        } else {
            lblTitle.setForeground(Color.decode("#cccccc"));
            lblTitle.setBorder(new MatteBorder(0, 0, 1, 0, new Color(0, 0, 0, 0)));
        }
        repaint();
    }

    public LoaiSP getData() {
        return data;
    }

    public void setData(LoaiSP data) {
        this.data = data;
    }

    public JLabel getLblTitle() {
        return lblTitle;
    }

    public void setLblTitle(JLabel lblTitle) {
        this.lblTitle = lblTitle;
    }

    public Category() {
        initComponents();
    }

    public void addData(LoaiSP data) {
        this.data = data;
        lblTitle.setText(data.getTenLoai());
    }

    private boolean toggleResult(boolean value) {
        return !value;
    }

    public void toggleActive() {
        setActive(toggleResult(active));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMinimumSize(new java.awt.Dimension(120, 30));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(120, 30));

        lblTitle.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("jLabel1");
        lblTitle.setMinimumSize(new java.awt.Dimension(41, 30));
        lblTitle.setPreferredSize(new java.awt.Dimension(41, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
