/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package test;

import com.boxcf.models.Box;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import javax.swing.border.MatteBorder;
import com.boxcf.models.DatBox;

/**
 *
 * @author PC
 */
public class ItemBill1 extends javax.swing.JPanel {
    
    DatBox datBox;
    private Box box;
    private EventItem1 event;

    public ItemBill1(DatBox datBox, Box box) {
        this.datBox = datBox;
        this.box = box;
    }
    
    
    
    public EventItem1 getEvent() {
        return event;
    }
    
    public void setEvent(EventItem1 event) {
        this.event = event;
    }
    
    public JLabel getBtnXoa() {
        return btnXoa;
    }
    
    public ItemBill1() {
        initComponents();
        setOpaque(false);
        setBorder(new MatteBorder(0, 0, 1, 0, Color.decode("#C8B6A6")));
//        btnXoa.addMouseListener(new MouseAdapter() {
//            @Override
//            public void mousePressed(MouseEvent me) {
//                if (SwingUtilities.isLeftMouseButton(me)) {
//                    event.itemClick(btnXoa, box);
//                }
//            }
//        });
    }
    
    public DatBox getData() {
        return this.datBox;
    }
    
    public void setData(DatBox datBox) {
        this.datBox = datBox;
        lblBox.setText(datBox.getMaBox() + "");
        lblSoluong.setText(datBox.getSoLuong() + "");
        lblGio.setText(datBox.getGioBD() + "");
//        lblGio.setText(datBox.getGioBD().getTime() + "");
    }
    
//    public void tangLen(int quantity) {
//        box.setSoLuong(quantity);
//        this.setData(box);
//        this.repaint();
//        this.revalidate();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSoluong = new javax.swing.JLabel();
        lblBox = new javax.swing.JLabel();
        btnXoa = new javax.swing.JLabel();
        lblGio = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(400, 40));
        setMinimumSize(new java.awt.Dimension(400, 40));
        setPreferredSize(new java.awt.Dimension(400, 40));

        lblSoluong.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        lblSoluong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSoluong.setText("01");

        lblBox.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        lblBox.setText("Dừa");

        btnXoa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/boxcf/images/icon/icons8_close_30px_2.png"))); // NOI18N
        btnXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblGio.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        lblGio.setText("230k");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBox, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSoluong, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblGio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblGio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnXoa;
    private javax.swing.JLabel lblBox;
    private javax.swing.JLabel lblGio;
    private javax.swing.JLabel lblSoluong;
    // End of variables declaration//GEN-END:variables
}
