/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package test;

import com.boxcf.components.ScrollBar;
import com.boxcf.models.Box;
import com.boxcf.models.DatBox;
import java.awt.Component;
import java.awt.FlowLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.SwingUtilities;
import test.EventIncrease;
import test.EventItem;
import test.Items;
import test.PanelBill;
import test.Store;

/**
 *
 * @author PC
 */
public class Order1 extends javax.swing.JPanel {

    private EventItem1 event;
    private boolean selected;
    private PanelBill1 panelBill;
    static DatBox boxDat;

    public Order1() {
        initComponents();
        scroll.setVerticalScrollBar(new ScrollBar());
        panelBill = new PanelBill1();
        jPanel1.setLayout(new FlowLayout());
        jPanel1.add(panelBill);
        Store.globelPanelBill = panelBill;

    }

    public void setEvent(EventItem1 event) {
        this.event = event;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new test.MainPanel();
        scroll = new javax.swing.JScrollPane();
        panelItem = new com.boxcf.components.PanelItem();
        mainPanel2 = new test.MainPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(1400, 731));
        setPreferredSize(new java.awt.Dimension(1400, 731));

        scroll.setBorder(null);
        scroll.setPreferredSize(new java.awt.Dimension(1000, 100));
        scroll.setViewportView(panelItem);

        mainPanel2.setPreferredSize(new java.awt.Dimension(400, 0));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hóa Đơn");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainPanel2Layout = new javax.swing.GroupLayout(mainPanel2);
        mainPanel2.setLayout(mainPanel2Layout);
        mainPanel2Layout.setHorizontalGroup(
            mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanel2Layout.setVerticalGroup(
            mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addComponent(mainPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 987, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1440, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 837, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private test.MainPanel mainPanel;
    private test.MainPanel mainPanel2;
    private com.boxcf.components.PanelItem panelItem;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables

    public void addData(Box box) {
        BoxItem boxItem = new BoxItem();
        boxItem.setData(box);
        boxItem.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent me) {
                if (SwingUtilities.isLeftMouseButton(me)) {
                    event.itemClick(boxItem, box);
                }
                
                //goi frame dat box --> truyen vao cai box dc click
                new DatBoxView(box).setVisible(true);
            }
        });

        panelItem.add(boxItem);
        panelItem.repaint();
        panelItem.revalidate();
        panelBill.setPanelItem(panelItem);
    }

    public void showItemBill(DatBox boxDat) {
//        System.out.println(selected + "2");
        panelBill.setList(boxDat);

        if (selected) { 
            panelBill.setList(boxDat);
        } else {
//            panelBill.removeItem(box);
        }
    }

    public boolean isSelected() {
        return selected;
    }

    public void setSelected(boolean selected) {
        this.selected = selected;
    }

    public void setEventIncreace(Component item, Box box) {
//        Items i = ((Items) item);

        // xử lí sự kiện giảm
//        i.getSoLuong().setEvenDecrease(new EventIncrease() {
//            @Override
//            public void itemClick(Component com, int quantity) {
//                // trừ 1 vì khi tăng lên số lượng bị châm hơn 1 số
//                panelBill.setQuantity(i.getData(), quantity - 1);
//
////                if (quantity <= 1) {
////                    panelBill.removeItem(box);
////                }
//            }
//
//        });
//
//        // xử lí sự kiện tăng
//        i.getSoLuong().setEvenIncrease(new EventIncrease() {
//            @Override
//            public void itemClick(Component com, int quantity) {
//                // cộng 1 vì khi tăng lên số lượng bị châm hơn 1 số
//                panelBill.setQuantity(i.getData(), quantity + 1);
//
//            }
//
//        });
    }

    //set che do dc chon
    public void setSelected(Component cpn) {
        BoxItem boxItem = ((BoxItem) cpn);

        if (boxItem.isSelected()) {
//            i.setSoLuong(0);
            boxItem.setSelected(false);

        } else {
//            boxItem.setSoLuong(1);
            boxItem.setSelected(true);
        }
//        setSelected(i.isSelected());
    }

}
